The active test run was aborted. Reason: Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/kaspir/projects/konstmsu/TradeAdvisor/TradeAdvisor.Test/bin/Debug/netcoreapp2.2/30dssae5.opv/SESprice-1.dat'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TradeAdvisor.HistoricalDataCache.CacheDay(Day day) in /Users/kaspir/projects/konstmsu/TradeAdvisor/TradeAdvisor/Program.cs:line 85
   at TradeAdvisor.HistoricalDataCache.EnsurePopulated(Day from, Day to) in /Users/kaspir/projects/konstmsu/TradeAdvisor/TradeAdvisor/Program.cs:line 73
   at TradeAdvisor.Test.HistoricalDataCacheTests.<>c.<<ShouldThrowForInvalidDays>b__2_0>d.MoveNext() in /Users/kaspir/projects/konstmsu/TradeAdvisor/TradeAdvisor.Test/HistoricalDataCacheTests.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

